# Basic R script to cluster/group some lat-longs about some predefined point and radius
require(RSocrata) # For pulling the data straight off OpenData
require(Cairo)
require(ggplot2)
require(ggmap)
require(dbscan)
options(stringsAsFactors = FALSE)
GeoData = read.socrata(url = "https://opendata.socrata.com/resource/txu4-fsic.csv?$select=longitude,latitude")
#GeoData = as.matrix(GeoData)
CairoWin()
MapBackground = get_map(location = c(-98.35,39.5), zoom = 4, scale = 2, maptype = "roadmap", source =  "google")
ggmap(MapBackground) + geom_point(data = GeoData, aes(x = Longitude, y = Latitude, colour = Facility.ID), size = 0.01)
GeoClust = dbscan(GeoData, eps = 1, minPts = 5)
GeoData$Cluster = matrix(unlist(GeoClust$cluster), ncol = 1, byrow = TRUE)
View(GeoData)
ggmap(MapBackground) + geom_point(data = testmatrix, aes(x = Longitude, y = Latitude, colour = Cluster), size = 0.01) +scale_colour_gradientn(colours = rainbow(40))