# Basic R script to cluster/group some lat-longs about some predefined point and radius
require(Cairo)
require(ggplot2)
require(ggmap)
require(geosphere)
require(dplyr)
require(DescTools)

options(stringsAsFactors = FALSE)

GeoData = read.csv(file = "fibreloc.csv", header = TRUE)
GeoCentres = read.csv(file = "ClusterCentres.csv", header = TRUE)
MapBackground = get_map(location = c(174.7633,-36.8485), zoom = 5, scale = "auto", maptype = "roadmap", source =  "google")
BlankList = vector(mode = "numeric",15)
GetClosest = function(templist, baseset, tempvector, a, b){ #a = 3,4 b = 2, 3
  for(i in 1:15){
    templist[i] = Closest(as.vector(baseset[,a]), tempvector[i,b])
  }
  return(templist)
}

NewCentres = as.matrix(data.frame(GetClosest(BlankList, GeoData, GeoCentres, 3, 2), GetClosest(BlankList, GeoData, GeoCentres, 4, 3)))
colnames(NewCentres) = c("Longitude", "Latitude")
Cluster = kmeans(x = as.matrix(GeoData[,3:4]), centers = NewCentres)
GeoData$Cluster = Cluster$cluster
write.table(GeoData, file = "GeoData.csv", sep = ",", row.names = FALSE)
write.table(Cluster$centers, file = "Cluster_Centres.csv", sep = ",", row.names = FALSE)
Cluster1 = subset(GeoData, Cluster == 1, select = c(GPS_Y, GPS_X))
Cluster2 = subset(GeoData, Cluster == 2, select = c(GPS_Y, GPS_X))
Cluster3 = subset(GeoData, Cluster == 3, select = c(GPS_Y, GPS_X))
Cluster4 = subset(GeoData, Cluster == 4, select = c(GPS_Y, GPS_X))
Cluster5 = subset(GeoData, Cluster == 5, select = c(GPS_Y, GPS_X))
Cluster6 = subset(GeoData, Cluster == 6, select = c(GPS_Y, GPS_X))
Cluster7 = subset(GeoData, Cluster == 7, select = c(GPS_Y, GPS_X))
Cluster8 = subset(GeoData, Cluster == 8, select = c(GPS_Y, GPS_X))
Cluster9 = subset(GeoData, Cluster == 9, select = c(GPS_Y, GPS_X))
Cluster10 = subset(GeoData, Cluster == 10, select = c(GPS_Y, GPS_X))
Cluster11 = subset(GeoData, Cluster == 11, select = c(GPS_Y, GPS_X))
Cluster12 = subset(GeoData, Cluster == 12, select = c(GPS_Y, GPS_X))
Cluster13 = subset(GeoData, Cluster == 13, select = c(GPS_Y, GPS_X))
Cluster14 = subset(GeoData, Cluster == 14, select = c(GPS_Y, GPS_X))
Cluster15 = subset(GeoData, Cluster == 15, select = c(GPS_Y, GPS_X))
write.table(Cluster1, file = "Cluster1.csv", sep = ",", row.names = FALSE, col.names = FALSE)
write.table(Cluster2, file = "Cluster2.csv", sep = ",", row.names = FALSE, col.names = FALSE)
write.table(Cluster3, file = "Cluster3.csv", sep = ",", row.names = FALSE, col.names = FALSE)
write.table(Cluster4, file = "Cluster4.csv", sep = ",", row.names = FALSE, col.names = FALSE)
write.table(Cluster5, file = "Cluster5.csv", sep = ",", row.names = FALSE, col.names = FALSE)
write.table(Cluster6, file = "Cluster6.csv", sep = ",", row.names = FALSE, col.names = FALSE)
write.table(Cluster7, file = "Cluster7.csv", sep = ",", row.names = FALSE, col.names = FALSE)
write.table(Cluster8, file = "Cluster8.csv", sep = ",", row.names = FALSE, col.names = FALSE)
write.table(Cluster9, file = "Cluster9.csv", sep = ",", row.names = FALSE, col.names = FALSE)
write.table(Cluster10, file = "Cluster10.csv", sep = ",", row.names = FALSE, col.names = FALSE)
write.table(Cluster11, file = "Cluster11.csv", sep = ",", row.names = FALSE, col.names = FALSE)
write.table(Cluster12, file = "Cluster12.csv", sep = ",", row.names = FALSE, col.names = FALSE)
write.table(Cluster13, file = "Cluster13.csv", sep = ",", row.names = FALSE, col.names = FALSE)
write.table(Cluster14, file = "Cluster14.csv", sep = ",", row.names = FALSE, col.names = FALSE)
write.table(Cluster15, file = "Cluster15.csv", sep = ",", row.names = FALSE, col.names = FALSE)